name: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)

variables:
  BuildConfiguration: 'Release'
  RepoName: 'Songhay.Dashboard'

trigger:
  batch: false
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - /azure*.yml
    - Songhay.Dashboard.Shell.Tests/*
    - Songhay.Dashboard.Tests/*

resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: |
     **/$(RepoName).Shell.csproj
     **/$(RepoName).Shell.Tests.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: mattlabrum.build-task.custom-build-task.downloadsSecureFile@0
  displayName: 'Download Secure File 27efdf69-4ae9-48a5-82d6-dde14d86aef0'
  inputs:
    fileInput: '27efdf69-4ae9-48a5-82d6-dde14d86aef0'
    targetPath: '$(RepoName).Shell'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/$(RepoName).Shell.Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(RepoName).Shell/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
