name: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  RepoName: 'Songhay.Dashboard'

resources:
- repo: self

steps:
- task: UseDotNet@2
  displayName: 'use .NET SDK 6.x'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.TempDirectory)/dotnet
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.fsproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: |
     **/$(RepoName).fsproj
     **/$(RepoName).Tests.fsproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/$(RepoName).Tests/*.fsproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test (server)'
  inputs:
    command: test
    projects: '**/$(RepoName).Server.Tests/*.fsproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish (Blazor Server)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './$(RepoName).Server/$(RepoName).Server.fsproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: bolero-drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'bolero-drop'
    publishLocation: 'Container'
