name: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)

pool:
  vmImage: windows-latest
  demands:
  - MSBuild

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  repoName: Songhay.Dashboard

resources:
- repo: self

steps:
- task: UseDotNet@2
  displayName: 'use .NET SDK 6.x'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    useGlobalJson: true

- powershell: |
    dotnet --info
  displayName: 'dotnet --info'

- task: VSBuild@1
  displayName: NuGet Restore
  inputs:
    msbuildArgs: '/t:Restore'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet build'
#   inputs:
#     projects: |
#      **/$(RepoName).fsproj
#      **/$(RepoName).Tests.fsproj
#     arguments: '--configuration $(BuildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet test'
#   inputs:
#     command: test
#     projects: '**/$(RepoName).Tests/*.fsproj'
#     arguments: '--configuration $(BuildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet test (server)'
#   inputs:
#     command: test
#     projects: '**/$(RepoName).Server.Tests/*.fsproj'
#     arguments: '--configuration $(BuildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet publish (Blazor Server)'
#   inputs:
#     command: 'publish'
#     publishWebProjects: false
#     projects: './$(RepoName).Server/$(RepoName).Server.fsproj'
#     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: bolero-drop'
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'bolero-drop'
#     publishLocation: 'Container'
