name: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  repoName: Songhay.Dashboard

resources:
- repo: self

steps:
- task: UseDotNet@2
  displayName: Use .NET SDK 6.x
  inputs:
    packageType: sdk
    version: 6.x

- powershell: |
    dotnet --info
  displayName: dotnet --info

- task: VSBuild@1
  displayName: NuGet Restore
  inputs:
    msbuildArgs: '/t:Restore'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '**\$(repoName).sln'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'

- task: VSTest@2
  displayName: Test
  inputs:
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testSelector: testAssemblies
    testAssemblyVer2: |
      '**\bin\**\$(repoName).Tests.dll'
      '**\bin\**\$(repoName).Server.Tests.dll'
      !**\obj\**

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: bolero-drop
    publishLocation: Container
