name: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release
  buildPlatform: Any CPU
  buildArtifactStagingDir: $(Build.ArtifactStagingDirectory)
  buildBinariesDirectory: $(Build.BinariesDirectory)
  buildLocalPath: $(Build.Repository.LocalPath)
  buildSourcesDir: $(Build.SourcesDirectory)
  commonTestResultsDir: $(Common.TestResultsDirectory)
  repoName: Songhay.Dashboard

resources:
- repo: self

steps:
- powershell: |
    Write-Host "displaying build locations..."
    Write-Host "buildArtifactStagingDir: $(Build.ArtifactStagingDirectory)"
    Write-Host "buildBinariesDirectory: $(Build.BinariesDirectory)"
    Write-Host "buildLocalPath: $(Build.Repository.LocalPath)"
    Write-Host "buildSourcesDir: $(Build.SourcesDirectory)"
    Write-Host "commonTestResultsDir: $(Common.TestResultsDirectory)"
  displayName: view build locations

- task: UseDotNet@2
  displayName: use .NET SDK 6.x
  inputs:
    packageType: sdk
    version: 6.x

- powershell: |
    dotnet --info
  displayName: dotnet --info

- powershell: |
    Write-Host "displaying current directory (it should be ``$(buildSourcesDir)``)..."
    Get-ChildItem -Path .\
  displayName: view current directory

- powershell: |
    dotnet restore $(repoName).sln  --verbosity normal
  displayName: dotnet restore

- powershell: |
    dotnet build $(repoName).sln --configuration $(buildConfiguration) --no-restore
  displayName: dotnet build [$(buildConfiguration)]

- powershell: |
    dotnet test $(repoName).Tests\$(repoName).Tests.fsproj --logger:trx --results-directory:$(commonTestResultsDir) --verbosity:normal --no-restore
  displayName: dotnet test [$(repoName).Tests]

- powershell: |
    dotnet test $(repoName).Server.Tests\$(repoName).Server.Tests.fsproj --logger:trx --results-directory:$(commonTestResultsDir) --verbosity:normal --no-restore
  displayName: dotnet test [$(repoName).Server.Tests]

- powershell: |
    dotnet publish $(repoName).Server\$(repoName).Server.fsproj --configuration $(buildConfiguration) --output $(buildBinariesDirectory) --no-restore
  displayName: dotnet publish [$(repoName).Server]

- powershell: |
    Write-Host "displaying ``buildBinariesDirectory`` (``$(buildBinariesDirectory)``)..."
    Get-ChildItem -Path $(buildBinariesDirectory)
  displayName: view `buildBinariesDirectory`

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(buildBinariesDirectory)
    includeRootFolder: true
    archiveType: zip
    archiveFile: $(buildArtifactStagingDir)/$(repoName).Server.zip
    replaceExistingArchive: true

- powershell: |
    Write-Host "displaying ``buildArtifactStagingDir`` (``$(buildArtifactStagingDir)``)..."
    Get-ChildItem -Path $(buildArtifactStagingDir)
  displayName: view `buildArtifactStagingDir`

- task: AzureRmWebAppDeployment@4
  displayName: deploy published artifact [STAGING]
  inputs:
    azureSubscription: 'Songhay System (Subscription scope; songhay-system-resources-free)'
    packageForLinux: $(buildArtifactStagingDir)/$(repoName).Server.zip
    WebAppName: songhay-system-staging
